knp_snappy:
    pdf:
        enabled:    true
        binary:     "%kernel.project_dir%/vendor/wemersonjanuario/wkhtmltopdf-windows/bin/64bit/wkhtmltopdf.exe"
        options:    []

    image:
        enabled:    true
        binary:     "%kernel.project_dir%/vendor/wemersonjanuario/wkhtmltopdf-windows/bin/64bit/wkhtmltopdf.exe"
        options:    []
